from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'pattern not found: {path}: {old[:100]!r}')
    p.write_text(text.replace(old, new, 1))

Path('backend/stack_reservations.py').write_text('''from __future__ import annotations\n\nfrom backend.server import db\n\nEPS = 1e-9\nACTIVE_STATUSES = ["Menunggu", "Sedang Dimuat"]\n\n\nasync def reserved_stack_qty(product_id: str, stack_code: str, exclude_load_id: str = "") -> float:\n    code = str(stack_code or "").strip().upper()\n    if not product_id or not code:\n        return 0.0\n    query = {"status": {"$in": ACTIVE_STATUSES}, "kondisi": "BAIK"}\n    if exclude_load_id:\n        query["id"] = {"$ne": exclude_load_id}\n    loads = await db.outbound_loads.find(query, {"_id": 0, "items": 1}).to_list(5000)\n    total = 0.0\n    for load in loads:\n        for item in load.get("items", []):\n            if item.get("productId") == product_id and str(item.get("stackCode") or "").strip().upper() == code:\n                total += float(item.get("qty", 0) or 0)\n    return total\n\n\nasync def available_stack_qty(product_id: str, stack_code: str, physical_qty: float, exclude_load_id: str = "") -> tuple[float, float]:\n    reserved = await reserved_stack_qty(product_id, stack_code, exclude_load_id)\n    return reserved, max(float(physical_qty or 0) - reserved, 0.0)\n''')

p = Path('backend/fefo_selection.py')
text = p.read_text()
text = text.replace('from backend.stack_lots import EPS, _n, expiry_status, lot_sort_key\n', 'from backend.stack_lots import EPS, _n, expiry_status, lot_sort_key\nfrom backend.stack_reservations import reserved_stack_qty\n')
text = text.replace('def build_fefo_pick_guide(product_id: str, allocations: list[dict], lots: list[dict]) -> dict:\n', 'def build_fefo_pick_guide(product_id: str, allocations: list[dict], lots: list[dict], reserved_by_stack: dict[str, float] | None = None) -> dict:\n    reserved_by_stack = reserved_by_stack or {}\n')
text = text.replace('''            "stackQty": physical,\n            "trackedQty": tracked,\n            "untrackedQty": max(physical - tracked, 0.0),\n''', '''            "stackQty": physical,\n            "reservedQty": max(_n(reserved_by_stack.get(code)), 0.0),\n            "availableQty": max(physical - max(_n(reserved_by_stack.get(code)), 0.0), 0.0),\n            "trackedQty": tracked,\n            "untrackedQty": max(physical - tracked, 0.0),\n''')
text = text.replace('''    integrity_error = any(row["overtrackedQty"] > EPS for row in rows)\n    legacy_rows = [row for row in rows if row["untrackedQty"] > EPS]\n    tracked_rows = [row for row in rows if row.get("nextLot")]\n''', '''    integrity_error = any(row["overtrackedQty"] > EPS for row in rows)\n    selectable_rows = [row for row in rows if row["availableQty"] > EPS]\n    legacy_rows = [row for row in selectable_rows if row["untrackedQty"] > EPS]\n    tracked_rows = [row for row in selectable_rows if row.get("nextLot")]\n''')
text = text.replace('''        recommended = [row["stackCode"] for row in rows]\n        mode = "LEGACY_ONLY" if rows else "NO_STOCK"\n        reason = "Belum ada lot terlacak; pilih tumpukan stok fisik yang tersedia."\n''', '''        recommended = [row["stackCode"] for row in selectable_rows]\n        mode = "LEGACY_ONLY" if selectable_rows else ("FULLY_RESERVED" if rows else "NO_STOCK")\n        reason = "Belum ada lot terlacak; pilih tumpukan stok fisik yang tersedia." if selectable_rows else "Seluruh stok tumpukan sedang direservasi antrean pemuatan aktif."\n''')
text = text.replace('''    return build_fefo_pick_guide(product_id, allocations, lots)\n''', '''    reserved_by_stack = {}\n    for allocation in allocations:\n        code = str(allocation.get("stackCode") or "").strip().upper()\n        if code and code not in reserved_by_stack:\n            reserved_by_stack[code] = await reserved_stack_qty(product_id, code)\n    return build_fefo_pick_guide(product_id, allocations, lots, reserved_by_stack)\n''')
p.write_text(text)

p = Path('backend/outbound_flow.py')
text = p.read_text()
text = text.replace('from backend.fefo_selection import get_fefo_pick_guide, selection_requires_reason\n', 'from backend.fefo_selection import get_fefo_pick_guide, selection_requires_reason\nfrom backend.stack_reservations import available_stack_qty\n')
old = '''    if multi_source and body.kondisi == "BAIK":\n        quantities_by_stack = defaultdict(float)\n        for item in load_items:\n            quantities_by_stack[(item["productId"], item["stackCode"])] += item["qty"]\n        active_loads = await db.outbound_loads.find({"status": {"$in": ["Menunggu", "Sedang Dimuat"]}, "kondisi": "BAIK"}, {"_id": 0, "items": 1}).to_list(5000)\n        for (product_id, stack_code), qty in quantities_by_stack.items():\n            allocation = await db.stack_allocations.find_one({"productId": product_id, "stackCode": stack_code}, {"_id": 0, "primaryQty": 1})\n            reserved = sum(float(line.get("qty", 0) or 0) for load in active_loads for line in load.get("items", []) if line.get("productId") == product_id and line.get("stackCode") == stack_code)\n            available = float((allocation or {}).get("primaryQty", 0) or 0) - reserved\n            if qty > available + 1e-9:\n                raise HTTPException(status_code=400, detail=f"Stok tumpukan {stack_code} untuk {products[product_id].get('name', '')} tidak cukup (tersedia {max(available, 0):g})")\n'''
new = '''    if body.kondisi == "BAIK":\n        quantities_by_stack = defaultdict(float)\n        for item in load_items:\n            quantities_by_stack[(item["productId"], item["stackCode"])] += item["qty"]\n        for (product_id, stack_code), qty in quantities_by_stack.items():\n            allocation = await db.stack_allocations.find_one({"productId": product_id, "stackCode": stack_code}, {"_id": 0, "primaryQty": 1})\n            physical = float((allocation or {}).get("primaryQty", 0) or 0)\n            reserved, available = await available_stack_qty(product_id, stack_code, physical)\n            if qty > available + 1e-9:\n                raise HTTPException(status_code=400, detail=f"Stok tumpukan {stack_code} untuk {products[product_id].get('name', '')} tidak cukup. Fisik {physical:g}, direservasi antrean lain {reserved:g}, tersedia {available:g}")\n'''
if old not in text:
    raise SystemExit('create reservation block not found')
text = text.replace(old, new, 1)
old_edit = '''        if stack_code:\n            allocation = await db.stack_allocations.find_one({"productId": submitted.productId, "stackCode": stack_code}, {"_id": 0, "primaryQty": 1})\n            if not allocation or float(allocation.get("primaryQty", 0) or 0) + 1e-9 < qty:\n                raise HTTPException(status_code=400, detail=f"Stok {product.get('name', '')} pada {stack_code} tidak mencukupi")\n'''
new_edit = '''        if stack_code:\n            allocation = await db.stack_allocations.find_one({"productId": submitted.productId, "stackCode": stack_code}, {"_id": 0, "primaryQty": 1})\n            physical = float((allocation or {}).get("primaryQty", 0) or 0)\n            reserved, available = await available_stack_qty(submitted.productId, stack_code, physical, exclude_load_id=load_id)\n            if not allocation or qty > available + 1e-9:\n                raise HTTPException(status_code=400, detail=f"Stok {product.get('name', '')} pada {stack_code} tidak mencukupi. Fisik {physical:g}, reservasi antrean lain {reserved:g}, tersedia {available:g}")\n'''
if old_edit not in text:
    raise SystemExit('edit reservation block not found')
text = text.replace(old_edit, new_edit, 1)
# Validate aggregate quantities too, for repeated lines using the same product+stack during edit.
needle = '''        revised_items.append({**previous, "documentNo": document_no, "qty": qty, "channel": channel, "berat": float(product.get("weight", 0) or 0) * qty, "loadingFee": _loading_fee(product, qty, charge_mode_override=(previous.get("loadingFee") or {}).get("mode", "")), "stackCode": stack_code, "crewGroup": _crew_group(stack_code or product.get("location", "")), "fefoPolicy": guide.get("policy", previous.get("fefoPolicy", "")) if guide else previous.get("fefoPolicy", ""), "fefoMode": guide.get("mode", previous.get("fefoMode", "")) if guide else previous.get("fefoMode", ""), "fefoRecommendedStacks": guide.get("recommendedStacks", previous.get("fefoRecommendedStacks", [])) if guide else previous.get("fefoRecommendedStacks", []), "fefoSelectionStatus": selection_status, "fefoExceptionReason": exception_reason if selection_status == "EXCEPTION" else ""})\n\n    now = now_iso()\n'''
repl = needle.replace('\n\n    now = now_iso()\n', '''\n\n    if load.get("kondisi", "BAIK") == "BAIK":\n        edit_by_stack = defaultdict(float)\n        for item in revised_items:\n            edit_by_stack[(item["productId"], item["stackCode"])] += float(item.get("qty", 0) or 0)\n        for (product_id, stack_code), qty in edit_by_stack.items():\n            allocation = await db.stack_allocations.find_one({"productId": product_id, "stackCode": stack_code}, {"_id": 0, "primaryQty": 1})\n            physical = float((allocation or {}).get("primaryQty", 0) or 0)\n            reserved, available = await available_stack_qty(product_id, stack_code, physical, exclude_load_id=load_id)\n            if qty > available + 1e-9:\n                raise HTTPException(status_code=400, detail=f"Total edit pada {stack_code} melebihi stok tersedia setelah reservasi antrean lain ({available:g})")\n\n    now = now_iso()\n''')
if needle not in text:
    raise SystemExit('edit aggregate needle not found')
text = text.replace(needle, repl, 1)
p.write_text(text)

p = Path('frontend/src/pages/CatatStok.jsx')
text = p.read_text()
old_func = '''    return (stackAllocations || [])\n      .filter((allocation) => allocation.productId === productId && Number(allocation.primaryQty || 0) > 0)\n      .sort((a, b) => {\n        const ac = String(a.stackCode || ''); const bc = String(b.stackCode || '');\n        const ap = priorities.has(ac) ? priorities.get(ac) : 9999; const bp = priorities.has(bc) ? priorities.get(bc) : 9999;\n        if (ap !== bp) return ap - bp;\n        const ae = meta.get(ac)?.nextLot?.exp || '9999-12-31'; const be = meta.get(bc)?.nextLot?.exp || '9999-12-31';\n        return ae.localeCompare(be) || ac.localeCompare(bc);\n      });\n'''
new_func = '''    return (stackAllocations || [])\n      .filter((allocation) => allocation.productId === productId && Number(allocation.primaryQty || 0) > 0)\n      .map((allocation) => {\n        const code = String(allocation.stackCode || '');\n        const physical = Number(allocation.primaryQty || 0);\n        const reservation = meta.get(code);\n        return { ...allocation, reservedQty: Number(reservation?.reservedQty || 0), availableQty: Number(reservation?.availableQty ?? physical) };\n      })\n      .filter((allocation) => Number(allocation.availableQty || 0) > 0)\n      .sort((a, b) => {\n        const ac = String(a.stackCode || ''); const bc = String(b.stackCode || '');\n        const ap = priorities.has(ac) ? priorities.get(ac) : 9999; const bp = priorities.has(bc) ? priorities.get(bc) : 9999;\n        if (ap !== bp) return ap - bp;\n        const ae = meta.get(ac)?.nextLot?.exp || '9999-12-31'; const be = meta.get(bc)?.nextLot?.exp || '9999-12-31';\n        return ae.localeCompare(be) || ac.localeCompare(bc);\n      });\n'''
if old_func not in text:
    raise SystemExit('frontend stack function not found')
text = text.replace(old_func, new_func, 1)
# Add early client validation before consignment validation.
needle = '''    if (type === 'KELUAR' && ['MEMO', 'ND'].includes(documentType) && consignmentDestination && !consignmentZone) {\n'''
insert = '''    if (type === 'KELUAR' && kondisi === 'BAIK') {\n      for (const row of chosen) {\n        const stack = availableStacksFor(row.productId).find((item) => item.stackCode === row.stackCode);\n        if (row.stackCode && stack && Number(row.qty || 0) > Number(stack.availableQty || 0)) {\n          toast.error(`Stok tersedia ${row.stackCode} tinggal ${formatNum(stack.availableQty || 0)} ${row.product.unit} setelah reservasi antrean lain`);\n          return;\n        }\n      }\n    }\n''' + needle
if needle not in text:
    raise SystemExit('frontend validation needle not found')
text = text.replace(needle, insert, 1)
old_option = '''const qty = Number(allocation.primaryQty || 0); const secondary = secondaryQty > 0 ? Math.floor(qty / secondaryQty) : 0; const remainder = secondaryQty > 0 ? qty - (secondary * secondaryQty) : 0; const packaging = secondaryQty > 0 ? ` · ${formatNum(secondary)} ${allocation.secondary || 'sekunder'}${remainder > 0 ? ` + ${formatNum(remainder)} ${allocation.unit || 'pcs'}` : ''}` : ''; const guide = fefoGuideFor(row.productId); const meta = fefoStackMeta(row.productId, allocation.stackCode); const recommended = guide?.recommendedStacks?.includes(allocation.stackCode); const expiry = meta?.nextLot?.exp ? ` · exp ${meta.nextLot.exp}` : (Number(meta?.untrackedQty || 0) > 0 ? ' · legacy' : ''); return <option key={allocation.id} value={allocation.stackCode}>{recommended ? '★ ' : ''}{allocation.stackCode} — sisa {formatNum(qty)} {allocation.unit || 'pcs'}{packaging}{expiry}</option>;'''
new_option = '''const qty = Number(allocation.primaryQty || 0); const availableQty = Number(allocation.availableQty ?? qty); const reservedQty = Number(allocation.reservedQty || 0); const secondary = secondaryQty > 0 ? Math.floor(availableQty / secondaryQty) : 0; const remainder = secondaryQty > 0 ? availableQty - (secondary * secondaryQty) : 0; const packaging = secondaryQty > 0 ? ` · ${formatNum(secondary)} ${allocation.secondary || 'sekunder'}${remainder > 0 ? ` + ${formatNum(remainder)} ${allocation.unit || 'pcs'}` : ''}` : ''; const guide = fefoGuideFor(row.productId); const meta = fefoStackMeta(row.productId, allocation.stackCode); const recommended = guide?.recommendedStacks?.includes(allocation.stackCode); const expiry = meta?.nextLot?.exp ? ` · exp ${meta.nextLot.exp}` : (Number(meta?.untrackedQty || 0) > 0 ? ' · legacy' : ''); const reservation = reservedQty > 0 ? ` · reservasi ${formatNum(reservedQty)}` : ''; return <option key={allocation.id} value={allocation.stackCode}>{recommended ? '★ ' : ''}{allocation.stackCode} — tersedia {formatNum(availableQty)} {allocation.unit || 'pcs'}{reservation}{packaging}{expiry}</option>;'''
if old_option not in text:
    raise SystemExit('frontend option body not found')
text = text.replace(old_option, new_option, 1)
p.write_text(text)

# Extend tests.
p = Path('backend/tests/test_subledgers.py')
text = p.read_text()
if 'build_fefo_pick_guide' not in text:
    text += '''\n\ndef test_fefo_guide_skips_fully_reserved_priority_stack():\n    from backend.fefo_selection import build_fefo_pick_guide\n    allocations = [\n        {"stackCode": "18/A01", "primaryQty": 100, "unit": "pack"},\n        {"stackCode": "18/A02", "primaryQty": 100, "unit": "pack"},\n    ]\n    lots = [\n        {"id": "l1", "stackCode": "18/A01", "remainingQty": 100, "exp": "2026-10-01", "status": "AKTIF"},\n        {"id": "l2", "stackCode": "18/A02", "remainingQty": 100, "exp": "2026-11-01", "status": "AKTIF"},\n    ]\n    guide = build_fefo_pick_guide("p1", allocations, lots, {"18/A01": 100})\n    assert guide["recommendedStacks"] == ["18/A02"]\n    row = next(item for item in guide["stacks"] if item["stackCode"] == "18/A01")\n    assert row["reservedQty"] == 100\n    assert row["availableQty"] == 0\n\n\ndef test_fefo_guide_reports_partial_stack_reservation():\n    from backend.fefo_selection import build_fefo_pick_guide\n    allocations = [{"stackCode": "19/B01", "primaryQty": 80, "unit": "pack"}]\n    guide = build_fefo_pick_guide("p1", allocations, [], {"19/B01": 25})\n    row = guide["stacks"][0]\n    assert row["reservedQty"] == 25\n    assert row["availableQty"] == 55\n    assert guide["recommendedStacks"] == ["19/B01"]\n'''
p.write_text(text)

print('stack reservation patch applied')
